takeout/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^hello/', include('hello.urls', namespace='hello')),
]

takeout/hello/urls.py


from django.conf.urls import url

from . import  views

#app_name = 'polls'
u'''
http://stackoverflow.com/questions/10059673/named-regular-expression-group-pgroup-nameregexp-what-does-p-stand-for
'''
urlpatterns = [
    #ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

takeout/index/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

takeout/index/templates/index/index.html
{% extends "base.html" %}
{% load %}

{% block title %}
"首页"
{% endblock title %}

{% block body %}
    <h1>main page</h1>
    <label for="">
        {% if user.is_authenticated %}
        <span>欢迎 '{{ user.get_username }}'</span>
        <a href="{% url 'index:logout' %}">退出</a>
        {% else %}
        <a href="{% url 'index:login' %}">登陆</a>
        <a href="{% url 'index:register' %}">注册</a>
        {% endif %}
    </label>
{% endblock body %}

takeout/index/templates/index/login.html
{% extends "base.html" %}

{% block title %} 登陆 {% endblock title %}

{% block body %}
<form method="POST" action="{% url 'index:login' %}">
    {% csrf_token %}
    <label for="username">username: <input name="username" id="username"></label><br><br>
    <label for="password">password: <input name="password" id="password"></label><br><br>
    <input type="submit" value="Vote" />
</form>

{% endblock body %}

takeout/index/templates/index/register.html
{% extends "base.html" %}

{% block title %} 注册 {% endblock title %}

{% block body %}

{# err --------- #}
{% if user_err %}
<strong>{{user_err}}</strong>
{% endif %}


<form method="POST" action="{% url 'index:register' %}">
    {% csrf_token %}
    <label for="username"><input name="username" id="username"></label><br><br>
    <label for="password"><input name="password" id="password"></label><br><br>
    <label for="password1"><input name="password1" id="password1"></label><br><br>
    <input type="submit" value="Vote" />
</form>

{% if err_msg %}
{{err_msg}}
{% endif %}
{% endblock body %}